<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('windows'))">net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">net9.0-android;net9.0-windows10.0.19041.0</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>DictMobile</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<ApplicationTitle>DictMobile</ApplicationTitle>
		<ApplicationId>com.companyname.dictMobile</ApplicationId>
		<ApplicationDisplayVersion>1.2</ApplicationDisplayVersion>
		<ApplicationVersion>3</ApplicationVersion>

		<WindowsPackageType>MSIX</WindowsPackageType>

		<!-- Platform versions -->
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</TargetPlatformMinVersion>

		<!-- Runtime architectures -->
		<RuntimeIdentifiers Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">android-arm64;android-arm;android-x64</RuntimeIdentifiers>
		<RuntimeIdentifier Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">win-x64</RuntimeIdentifier>

		<!-- App metadata -->
		<FileVersion>1.4</FileVersion>
		<RepositoryUrl>https://github.com/t232006/DictMobileMaui</RepositoryUrl>
		<PackageIcon>dictIcon128.png</PackageIcon>
		<SignAssembly>False</SignAssembly>
		<AssemblyTitle>Personal Dictionary</AssemblyTitle>

		<!-- Android signing -->
		<AndroidSigningKeyStore>mynew.keystore</AndroidSigningKeyStore>

		<!-- Windows packaging -->
		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
		<PackageCertificateThumbprint>E2F53C61F66D02F44D4C6948F8127075C92EDF26</PackageCertificateThumbprint>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>

		<UserSecretsId>5339ce82-c9eb-43b4-9926-de8afcf80019</UserSecretsId>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
		<AndroidPackageFormat>apk</AndroidPackageFormat>
		<AndroidKeyStore>True</AndroidKeyStore>
		<AndroidSigningStorePass>489259383</AndroidSigningStorePass>
		<AndroidSigningKeyAlias>myappkey</AndroidSigningKeyAlias>
		<AndroidSigningKeyPass>489259383</AndroidSigningKeyPass>
		<ApplicationDisplayVersion>1.4</ApplicationDisplayVersion>
		<ApplicationVersion>4</ApplicationVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-android|AnyCPU'">
		<AndroidKeyStore>True</AndroidKeyStore>
		<AndroidSigningStorePass>489259383</AndroidSigningStorePass>
		<AndroidSigningKeyAlias>myappkey</AndroidSigningKeyAlias>
		<AndroidSigningKeyPass>489259383</AndroidSigningKeyPass>
		<ApplicationDisplayVersion>1.4</ApplicationDisplayVersion>
		<ApplicationVersion>4</ApplicationVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationDisplayVersion>1.4</ApplicationDisplayVersion>
	  <ApplicationVersion>4</ApplicationVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationDisplayVersion>1.4</ApplicationDisplayVersion>
	  <ApplicationVersion>4</ApplicationVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.png" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\appicon.png" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Remove="Resources\Images\drive_from.png" />
		<MauiImage Remove="Resources\Images\drive_to.png" />
		<MauiImage Remove="Resources\Images\W.png" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
		<AndroidResource Remove="Platforms\Android\Resources\xml\network_security_config.xml" />
		<MauiAsset Remove="Resources\Raw\dictionary_empty.db" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\Images\W.png" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\Images\drive_from.png" />
		<EmbeddedResource Include="Resources\Images\drive_to.png" />
		<EmbeddedResource Include="Resources\Raw\dictionary.db">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\Images\add.png" />
		<EmbeddedResource Include="Resources\Images\add1.png" />
		<EmbeddedResource Include="Resources\Images\arrow_right.png" />
		<EmbeddedResource Include="Resources\Images\arrow_right_from.png" />
		<EmbeddedResource Include="Resources\Images\arrow_right_to.png" />
		<EmbeddedResource Include="Resources\Images\cancel.png" />
		<EmbeddedResource Include="Resources\Images\check_mark.png" />
		<EmbeddedResource Include="Resources\Images\cloud_from.png" />
		<EmbeddedResource Include="Resources\Images\cloud_to.png" />
		<EmbeddedResource Include="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		<EmbeddedResource Include="Resources\Images\edit1.png" />
		<EmbeddedResource Include="Resources\Images\eye.png" />
		<EmbeddedResource Include="Resources\Images\folder_small.png" />
		<EmbeddedResource Include="Resources\Images\ok.png" />
		<EmbeddedResource Include="Resources\Images\play_small.png" />
		<EmbeddedResource Include="Resources\Images\search.png" />
		<EmbeddedResource Include="Resources\Images\trash_bin_small.png" />
		<EmbeddedResource Include="Resources\Raw\dictionary_empty.db" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\..\..\icons\dictIcon128.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Google.Apis.Auth" Version="1.74.0" />
		<PackageReference Include="Google.Apis.Drive.v3" Version="1.74.0.4135" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="System.Runtime" Version="4.3.1" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.120" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.10" />
		<PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.120" />
		<PackageReference Include="sqlite-net" Version="1.6.292" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Pages\AccordancePage.xaml.cs">
			<DependentUpon>AccordancePage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Pages\Card\Card.xaml.cs">
		  <DependentUpon>Card.xaml</DependentUpon>
		</Compile>
		<Compile Update="Pages\Card\Know_Dont.xaml.cs">
		  <DependentUpon>Know_Dont.xaml</DependentUpon>
		</Compile>
		<Compile Update="Pages\Card\CardGame.xaml.cs">
		  <DependentUpon>CardGame.xaml</DependentUpon>
		</Compile>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="Pages\BasePage.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\AccordancePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\Card\Card.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\Card\Know_Dont.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\Card\CardGame.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\LoadingPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Pages\TestPage.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\CardStyles.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\TestStyles.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

</Project>